#:schema node_modules/wrangler/config-schema.json
name = "sublink-worker-0"
main = "src/worker.jsx"
compatibility_date = "2024-07-24"
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
  { binding = "SUBLINK_KV", id = "bd43bd8d7d4345a49e97cde0d873f9b9" }
]

[assets]
directory = "./public"
